### ISSUE TITLE
Do you support comments?

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [The-Eye-Team/reddit-dl#2]
Your README says you do not support comments, but comments.go exists and was latest commited with commit `add support for downloading comments`, This conflicting language is confusing.

**Comment by nektro** [comment]
It does yes, but in that commit I forgot to remove the line in the README. My apologies for the confusion but comments \*are\* supported.

**Comment by gidoBOSSftw5731** [comment]
Ah, well, thanks for the clarification
